input:
  broker:
    inputs:
    - kafka_balanced:
        addresses:
        - ${KAFKA_BROKERS}
        client_id: ${CLIENT_ID}
        consumer_group: ${CONSUMER_GROUP}
        topics:
        - embedded_events.file_transfer.upload.request.1_0

pipeline:
  processors:
  - log:
      level: INFO
      fields: {}
      message: ""

output:
  type: drop


