input:
  broker:
    inputs:
    - kafka_balanced:
        addresses:
        - kafka.kafka:9092
        client_id: digestor_kafka_input
        consumer_group: digestor
        topics:
        - ingestor_stream

pipeline:
  processors:
  - log:
      level: INFO
      fields: {}
      message: ""

output:
  type: drop


