apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch-curator
  namespace: logging
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: elasticsearch-curator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: elasticsearch-curator
    version: 2.1.3
  values:
    cronjob:
      schedule: 0 15 * * *
    configMaps:
      action_file_yml: |-
        ---
        actions:
          1:
            action: delete_indices
            description: "Clean up ES by deleting old indices"
            options:
              timeout_override:
              continue_if_exception: False
              disable_action: False
              ignore_empty_list: True
            filters:
            - filtertype: age
              source: name
              direction: older
              timestring: '%Y.%m.%d'
              unit: days
              unit_count: 1
              field:
              stats_result:
              epoch:
              exclude: False
      config_yml: |-
        ---
        client:
          hosts:
            - elasticsearch-master
          port: 9200
