apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: elasticsearch
  chart:
    repository: https://helm.elastic.co/
    name: elasticsearch
    version: 7.5.2
  values:
    replicas: 2
    minimumMasterNodes: 1
    ingress:
      enabled: true
      hosts:
      - elasticsearch.domain.com
