apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: kibana
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.5.2
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"

