input:
  http_server:
    address: ""
    path: /
    timeout: 5s
    rate_limit: ""

pipeline:
  processors:
  - log:
      level: INFO
      fields: {}
      message: ""

output:
  kafka:
    addresses:
    - kafka.kafka:9092
    topic: ingestor_stream
    client_id: ingestor_kafka_output
    batching:
      count: 1
      byte_size: 0
      period: ""
