input:
  type: http_server

pipeline:
  processors:
  - log:
      level: INFO
      fields: {}
      message: ""

output:
  type: kafka
  kafka:
    addresses:
    - kafka.kafka:9092
    topic: ingestor_stream
    client_id: ingestor_kafka_output
    batching:
      count: 1
      byte_size: 0
      period: ""
