apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch-exporter
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: elasticsearch-exporter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: elasticsearch-exporter
    version: 2.2.0
  values:
    replicaCount: 1
    es:
      uri: http://elasticsearch-master.logging:9200
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus-operator
