apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: external-dns
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: external-dns
    version: 2.15.3
  values:
    aws:
      region: eu-west-1


