apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kafka-minion
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: kafka-minion
  chart:
    repository: https://raw.githubusercontent.com/cloudworkz/kafka-minion-helm-chart/master
    name: kafka-minion
    version: 1.1.2
  values:
    kafka:
      brokers: kafka1.domain.com:9092,kafka2.domain.com:9092,kafka3.domain.com:9092
    serviceMonitor:
      create: true
    logLevel: info
