apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.7.0
  values:
    grafana:
      enabled: true
      ingress:
        enabled: true
        hosts:
        - grafana.domain.com
      dashboards:
          prometheus-stats:
            gnetId: 2
            revision: 2
            datasource: Prometheus
          node-exporter:
            gnetId: 11074
            revision: 2
            datasource: Prometheus
          kafka-minion:
            gnetId: 11074
            revision: 3
            datasource: Prometheus
          kafka-minion-ops:
            gnetId: 11074
            revision: 2
            datasource: Prometheus
      plugins:
      - raintank-worldping-app
      - grafana-worldmap-panel
      - grafana-clock-panel
      - grafana-piechart-panel
      - ryantxu-ajax-panel
      - farski-blendstat-panel
      - briangann-gauge-panel
      - grafana-kubernetes-app
      - novalabs-annotations-panel
      - jdbranham-diagram-panel
      - digrich-bubblechart-panel
      - simpod-json-datasource
      - snuids-radar-panel
      - grafana-sensu-app
      - mxswat-separator-panel
      - snuids-trafficlights-panel
    prometheus:
      ingress:
        enabled: true
        hosts:
        - prometheus.domain.com
    prometheusOperator:
      createCustomResource: true
