apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~2.0
spec:
  releaseName: prometheus-adapter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-adapter
    version: 2.0.1
  values:
    prometheus:
      url: prometheus-operator-prometheus
      port: 9090
