apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~2.9
spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.9.0
