apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: letsencrypt-route53-secret-key
  namespace: cert-manager
spec:
  encryptedData:
    route53_certbot_secret_key: AgAEcptIWpHw+IN68kxqxaFhyjynT9DSfo9fAG/VMNUaiCZfKHbHc1V+JZfKAACMvUhKd1T0p+1DipM+vVdqekBTAXKj1UBXX1DHgxt4yNpcZ8FvQ+8C3o+SSAd2RlcUPAXeu6xEwkWuGQeA6kzoBuJtE6BINNJ3/9XDgL1CJ71JxvdT4Ad9yeOyHl2Ju9VngdYdvfRJwU3nOKVlQcEcN/jpirl3lzjCKl/SRO1fBDRFAYuCeyDNsNuV95DXfRk5xIdEzdxrZlhO0F+YSncsYcHt7nRoTez4BJVLL1PvH2O1A5S+Y/x3mQ7RGfTuMjqxmuHhFnpwFA1wJR2P0pgESQZrPjB2RwVqKwxTFxrg7018xQwk7M1UtbSZhDHHzfb0G3R5cwTMKt0FCpVM6e9K8yPUZOIx2Q2OOIL4Dmw9wConKztmWVPkEMrK+pXoMm29frtiySUzzP6QQta0L1zUTQhsNFvMzIzMvlCHwHllEBX08fShBGUm5QbxmF+zWdgFEBgjIGIeAN6IKw2SHWMob7zfaG6bnxn3asS5OviYHTeTk7sroZV6ATGaN6toWu01sBaCDAVR9CZ6VINLdb4etmk2FJw9A/gaofWPzDjos9H7t0V32YrlkGolCLJ95vRTNNqL+CndHSoex1SCxXWQ1qYjHC0ZSCNiT7KBNm584QUtEZm6KJcDYFiF+GhwtleUt7M4REoId459dz7frlAbquZ+1twusG6Cuy/ovbdrdcz1DlXWmWCK2oCy
  template:
    metadata:
      creationTimestamp: null
      name: letsencrypt-route53-secret-key
      namespace: cert-manager
status: {}