---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api-ingestor
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  chart:
    git: git@github.com:mfamador/data-pipeline-gitops
    path: charts/api-ingestor
    ref: master
  values:
    image:
      repository: marcoamador/pipeline-ingestor
      tag: 1.0.1
      pullPolicy: Always
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
      hosts:
      - host: "ingestor.domain.com"
        paths: ["/"]
    env:
    - name: KAFKA_BROKERS
      value: kafka.kafka:9092
