---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app-digestor
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  chart:
    git: git@github.com:mfamador/data-pipeline-gitops
    path: charts/app-digestor
    ref: master
  values:
    image:
      repository: marcoamador/pipeline-digestor
      tag: 1.0.0
      pullPolicy: Always
    replicaCount: 1
    env:
    - name: KAFKA_BROKERS
      value: kafka.kafka:9092
    - name: CONSUMER_GROUP
      value: data_pipeline
